version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_app
    environment:
      POSTGRES_DB: reread
      POSTGRES_USER: reread
      POSTGRES_PASSWORD: spupassword
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database.sql:/docker-entrypoint-initdb.d/database.sql
      - ./data/postgres:/var/lib/postgresql/data # การเก็บข้อมูล docker ไปยังโฟลเดอร์ data
    ports:
      - "5432:5432"
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin_spu
    environment:
      PGADMIN_DEFAULT_EMAIL: reread@spulive.net
      PGADMIN_DEFAULT_PASSWORD: spuadmin
    volumes:
      - ./data/pgadmin:/var/lib/pgadmin # การเก็บข้อมูล docker ไปยังโฟลเดอร์ data
    ports:
      - "5050:80"
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  postgres_data: